// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bff

import (
	"github.com/KNICEX/InkFlow/internal/bff/internal/web"
	"github.com/KNICEX/InkFlow/internal/code"
	"github.com/KNICEX/InkFlow/internal/user"
	"github.com/KNICEX/InkFlow/pkg/ginx"
	"github.com/KNICEX/InkFlow/pkg/ginx/jwt"
	"github.com/KNICEX/InkFlow/pkg/ginx/middleware"
	"github.com/KNICEX/InkFlow/pkg/logx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitBff(userSvc user.Service, service3 user.OAuth2Service[user.GithubInfo], codeSvc code.Service, jwtHandler jwt.Handler, auth middleware.Authentication, log logx.Logger) []ginx.Handler {
	userHandler := web.NewUserHandler(userSvc, codeSvc, jwtHandler, auth, log)
	githubOAuth2Handler := web.NewGithubOAuth2Handler(service3, userSvc, jwtHandler, log)
	v := InitHandlers(userHandler, githubOAuth2Handler)
	return v
}

// wire.go:

var handlers = wire.NewSet(web.NewUserHandler)

func InitHandlers(uh *web.UserHandler, goh *web.GithubOAuth2Handler) []ginx.Handler {
	return []ginx.Handler{uh, goh}
}
