// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ink

import (
	"github.com/KNICEX/InkFlow/internal/ink/internal/repo"
	"github.com/KNICEX/InkFlow/internal/ink/internal/repo/cache"
	"github.com/KNICEX/InkFlow/internal/ink/internal/repo/dao"
	"github.com/KNICEX/InkFlow/internal/ink/internal/service"
	"github.com/KNICEX/InkFlow/pkg/logx"
	"github.com/KNICEX/InkFlow/pkg/snowflakex"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitInkService(cmd redis.Cmdable, db *gorm.DB, l logx.Logger) service.InkService {
	liveDAO := dao.NewLiveDAO(db)
	inkCache := cache.NewRedisInkCache(cmd)
	liveInkRepo := repo.NewCachedLiveInkRepo(liveDAO, inkCache, l)
	node := initSnowflakeNode()
	draftDAO := initDraftDAO(db, node)
	draftInkRepo := repo.NewNoCacheDraftInkRepo(draftDAO)
	inkService := service.NewInkService(liveInkRepo, draftInkRepo, l)
	return inkService
}

// wire.go:

func initSnowflakeNode() snowflakex.Node {
	return snowflakex.NewNode(snowflakex.DefaultStartTime, 0)
}

func initDraftDAO(db *gorm.DB, node snowflakex.Node) dao.DraftDAO {
	if err := dao.InitTable(db); err != nil {
		panic(err)
	}
	return dao.NewDraftDAO(db, node)
}
