// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/KNICEX/InkFlow/internal/bff"
	"github.com/KNICEX/InkFlow/internal/code"
	"github.com/KNICEX/InkFlow/internal/email"
	"github.com/KNICEX/InkFlow/internal/ink"
	"github.com/KNICEX/InkFlow/internal/interactive"
	"github.com/KNICEX/InkFlow/internal/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := InitLogger()
	db := InitDB(logger)
	universalClient := InitRedisUniversalClient()
	cmdable := InitRedisCmdable(universalClient)
	userService := user.InitUserService(db, cmdable, logger)
	service := email.InitMemoryService()
	serviceService := code.InitEmailCodeService(cmdable, service)
	inkService := ink.InitInkService(cmdable, db, logger)
	interactiveService := interactive.InitInteractiveService(cmdable, db, logger)
	handler := InitJwtHandler(cmdable)
	authentication := InitAuthMiddleware(handler, logger)
	v := bff.InitBff(userService, serviceService, inkService, interactiveService, handler, authentication, logger)
	engine := InitGin(v, logger)
	app := &App{
		Server: engine,
	}
	return app
}

// wire.go:

var thirdPartSet = wire.NewSet(
	InitLogger,
	InitDB,
	InitEs,
	InitRedisUniversalClient,
	InitRedisCmdable,
)

var webSet = wire.NewSet(
	InitJwtHandler,
	InitAuthMiddleware,
)
