// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notification

import (
	"github.com/IBM/sarama"
	"github.com/KNICEX/InkFlow/internal/comment"
	"github.com/KNICEX/InkFlow/internal/ink"
	"github.com/KNICEX/InkFlow/internal/notification/internal/event"
	"github.com/KNICEX/InkFlow/internal/notification/internal/repo"
	"github.com/KNICEX/InkFlow/internal/notification/internal/repo/dao"
	"github.com/KNICEX/InkFlow/internal/notification/internal/service"
	"github.com/KNICEX/InkFlow/pkg/logx"
	"github.com/KNICEX/InkFlow/pkg/snowflakex"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitNotificationService(db *gorm.DB) service.NotificationService {
	node := initSnowflakeNode()
	notificationDAO := initDAO(db, node)
	notificationRepo := repo.NewNoCacheNotificationRepo(notificationDAO)
	notificationService := service.NewNotificationService(notificationRepo)
	return notificationService
}

// wire.go:

func initSnowflakeNode() snowflakex.Node {
	return snowflakex.NewNode(snowflakex.DefaultStartTime, 0)
}

func initDAO(db *gorm.DB, node snowflakex.Node) dao.NotificationDAO {
	if err := dao.InitTables(db); err != nil {
		panic(err)
	}
	return dao.NewGormNotificationDAO(db, node)
}

func InitNotificationConsumer(cli sarama.Client, svc Service, inkSvc ink.Service, commentSvc comment.Service, l logx.Logger) *event.NotificationConsumer {
	consumer := event.NewNotificationConsumer(cli, svc, l)
	userFollowHandler := event.NewFollowHandler(svc)
	commentReplyHandler := event.NewReplyHandler(svc, commentSvc, inkSvc)
	commentLikeHandler := event.NewCommentLikeHandler(svc, commentSvc)
	inkLikeHandler := event.NewInkLikeHandler(svc, inkSvc)

	err := consumer.RegisterHandler(userFollowHandler, commentReplyHandler, commentLikeHandler, inkLikeHandler)
	if err != nil {
		panic(err)
	}
	return consumer
}
