postgres:
  dsn: "host=localhost user=root password=root dbname=ink_flow port=15432"
redis:
  addr: 127.0.0.1:16379
  password: 123456

#es:
#  addr: 127.0.0.1:9200
#  sniff: false

meilisearch:
  addr: http://127.0.0.1:7700
  master_key: your_master_key

email:
  smtp:
    username: example@gmail.com
    password: password
    port: 587
    host: smtp.gmail.com
    from_name: InkFlow

llm:
  gemini:
    key: key

otel:
  grpc:
    endpoint: localhost:4317
    insecure: true

kafka:
  addrs:
    - localhost:9094

file:
  cloudinary:
    key: your_key
    secret: your_secret
    cloud_name: your_cloud_name

temporal:
  addr: localhost:7233
  namespace: inkflow
  domain: default

gorse:
  addr: http://localhost:8088
#  default is empty
  api_key: your_api_key