// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package search

import (
	"github.com/KNICEX/InkFlow/internal/search/internal/repo"
	"github.com/KNICEX/InkFlow/internal/search/internal/repo/dao"
	"github.com/KNICEX/InkFlow/internal/search/internal/service"
	"github.com/meilisearch/meilisearch-go"
)

// Injectors from wire.go:

func InitSyncService(meili meilisearch.ServiceManager) service.SyncService {
	userDAO := dao.NewMeiliUserDAO(meili)
	userRepo := repo.NewUserRepo(userDAO)
	inkDAO := initInkDAO(meili)
	inkRepo := repo.NewInkRepo(inkDAO)
	commentDAO := dao.NewMeiliCommentDAO(meili)
	commentRepo := repo.NewCommentRepo(commentDAO, userDAO)
	syncService := service.NewSyncService(userRepo, inkRepo, commentRepo)
	return syncService
}

// wire.go:

func InitSearchService() Service {
	return nil
}

func initInkDAO(meili meilisearch.ServiceManager) dao.InkDAO {
	if err := dao.InitMeili(meili); err != nil {
		panic(err)
	}
	return dao.NewMeiliInkDAO(meili)
}
